### PR TITLE
Fix #9: Updated Styles

### LINKED ISSUE #9: Adding and Correcting Styles in the Landing Page
Screenshot (1105)
-> Centering main content in the hero section.
-> Adding 3D effect and animations to button and styling them to look professional.
-> Fixing an image issue in Most Loved Places section and adding cards.
-> Adding good fonts to make the website look more professional.

Please assign me this issue

### PR DESCRIPTION
**Pull request by Dinkar850**
Fix: #9 
->Centered content in the Hero Section
->Styled 'Book' button and added animation
->Corrected alignment issues and border radius on hover in Most Visited Places Section
->Replaced checkbox with icons and added relevant styles
->Corrected typography issues

Screenshot (1107)

It looks perfect with a 75 percent zoom from my screen size and with that size I am looking forward to add responsiveness to the Landing Page as well.  

Please review

### CODE REVIEW

**Comment by Dinkar850** [comment]
Adding on to this, I might be having a smaller screen size and I am planning to make the website responsive. It'll look something like this: 
Screenshot (1107)

The website will look more professional by reducing the entire size by a factor of 0.75 and then adding responsiveness.

**Comment by Nikhil-gi** [comment]
to @Dinkar850 
However, before merging, I’d like to request the removal of the date and search options from the home page, as these elements are now part of the booking page. This will help maintain clarity and avoid redundancy.

Once that’s updated, I’ll be happy to move forward with the merge. 
Thanks again for your contribution!

**Comment by Dinkar850** [comment]
@Nikhil-gi 

Sure will do that

**Comment by Dinkar850** [comment]
@Nikhil-gi 
I have updated the content as requested and have raised a new PR #18 
Please review!

**Comment by Dinkar850** [comment]
@Nikhil-gi 
I have added the following changes: 
- Removed the search and date fields and replaced it with a "Book Your Next Tour Now!" button.
- Corrected alignments in the "Most Visited Places" section here itself, which was a part of issue #15 

Screenshot (1110)

**Comment by Nikhil-gi** [comment]
Hi @Dinkar850 ,

Thank you for making the updates! I appreciate the removal of the search and date fields and replacing them with the "Book Your Next Tour Now!" button. The scaled animation on the button is a nice touch, and I also appreciate the alignment corrections in the "Most Visited Places" section.

Everything looks good now, and I’ll proceed with merging your changes. Thanks again for your hard work and contributions!

**Comment by Dinkar850** [comment]
@Nikhil-gi 
Thank you so much for your kind consideration.

**Pull request merged**
