### PR TITLE
Created a Blog Page for better Engagement and Highlights 

### PR DESCRIPTION
**Pull request by sajalgarg45**
In this page, I created a travel blog layout titled "Wander Nest Blog" with a responsive design. The page features a header with a navigation menu, a hero section with a background image and call-to-action button, and a section showcasing various blog posts displayed in cards. Each blog post has an image, title, brief description, and a centered "Read More" button. The layout is enhanced with consistent styling, including a uniform color scheme, background adjustments, and hover effects for interactivity, providing a professional and polished user experience
All the page is very responsive and have hover effect and can add more things in it .

Screenshot 2024-10-06 at 12 10 46 AM

Screenshot 2024-10-06 at 12 11 07 AM

Screenshot 2024-10-06 at 12 10 42 AM

### CODE REVIEW

**Comment by sajalgarg45** [comment]
Hey Nikhil Bro I have high hopes from your Repo and I wish my contributions will be able to merge it

**Comment by Nikhil-gi** [comment]
Hi @sajalgarg45 ,

Thank you for creating the blog page! Adding a blog is a fantastic idea to improve engagement and highlight key topics.

Before we proceed, I’d suggest aligning the blog page's design more closely with the home page to maintain a consistent theme across the site. Once the styling is updated to match the overall aesthetic, I’ll merge the changes.
Thanks again for your contribution!

Best regards,
@Nikhil-gi

**Comment by sajalgarg45** [comment]
Bro can You merge It this way , so that I will make another commit to change the css , please its a request ..
I hope you understand

**Comment by sajalgarg45** [comment]
Bro I have updated the css and made my blog page similar to that theme of your website 
I wish now you will merge my pull request I hope you will ..


Screenshot 2024-10-06 at 3 51 27 PM

Screenshot 2024-10-06 at 3 51 34 PM

Screenshot 2024-10-06 at 3 51 02 PM

Screenshot 2024-10-06 at 3 51 21 PM

**Comment by Nikhil-gi** [comment]
Hi @sajalgarg45 ,
Thank you for updating the CSS and aligning the blog page with the overall theme of the website! The design now looks much more consistent. I appreciate your effort and attention to detail.
I’ll go ahead and merge your pull request. Thanks again for your valuable contribution!

**Comment by sajalgarg45** [comment]
a very very thank you , I appreciate your work and willing to do more work with you , thank you

**Comment by sajalgarg45** [comment]
bro I guess , this pull request you merged does not show Hacktoberfest tag , can you update it , or tell me its required or not ..

**Pull request merged**
